---
- name: Installing cQube
  hosts: "{{ my_hosts }}"
  gather_facts: true
  become: true
  remote_user: root
  vars_files:
    - constants.yml
  roles:
          - angular
          - angular_admin

