- name: Run teacher attendance python code
  shell: "{{ base_dir }}/cqube/emission_app/flaskenv/bin/python {{ base_dir }}/cqube/emission_app/python/deploy_nifi.py teacher_attendance_transformer teacher_attendance_parameters 4666"
  tags: [ install, update ]

- name: Connection of teacher attendance to cqube data storage
  shell: "{{ base_dir }}/cqube/emission_app/flaskenv/bin/python {{ base_dir }}/cqube/emission_app/python/connect_nifi_processors.py cQube_data_storage teacher_attendance_transformer"  
  tags: [ install, update ]

- name: run python code to disable the processors
  shell: "{{ base_dir }}/cqube/emission_app/flaskenv/bin/python {{ base_dir }}/cqube/emission_app/python/nifi_disable_processor.py teacher_attendance_transformer {{ storage_type }}"
  tags: [ install, update ]  
