- name: Run static python code
  shell: "{{ base_dir }}/cqube/emission_app/flaskenv/bin/python {{ base_dir }}/cqube/emission_app/python/deploy_nifi.py static_data_transformer static_data_parameters 0"
  tags: [ install, update ]

- name: Connection of static to cqube data storage
  shell: "{{ base_dir }}/cqube/emission_app/flaskenv/bin/python {{ base_dir }}/cqube/emission_app/python/connect_nifi_processors.py cQube_data_storage static_data_transformer"
  tags: [ install, update ]

- name: run python code to disable the processors
  shell: "{{ base_dir }}/cqube/emission_app/flaskenv/bin/python {{ base_dir }}/cqube/emission_app/python/nifi_disable_processor.py static_data_transformer {{ storage_type }}"
  tags: [ install, update ]  
